# Generated by Django 3.1.4 on 2020-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='currency',
            field=models.CharField(choices=[('EGP', 'EGP'), ('$', '$'), ('€', '€'), ('£', '£')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Visa', 'Visa')], max_length=64, null=True),
        ),
    ]
