# Generated by Django 3.1.4 on 2021-01-06 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0008_auto_20210106_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True , blank=True, on_delete=django.db.models.deletion.CASCADE, to='Marketplace.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marketplace.customer'),
        ),
    ]
