# Generated by Django 3.1.4 on 2021-01-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0010_auto_20210106_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
