# Generated by Django 3.1.4 on 2021-01-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0012_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
