# Generated by Django 3.1.4 on 2021-01-06 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0013_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True , blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True , blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True , blank=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marketplace.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketplace.product')),
            ],
        ),
    ]
