# Generated by Django 3.1.4 on 2021-01-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0015_auto_20210106_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='date',
        ),
    ]
