# Generated by Django 3.1.4 on 2021-01-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0017_checkout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='date',
        ),
    ]
