# Generated by Django 3.1.4 on 2021-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0021_auto_20210106_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.IntegerField(max_length=1),
        ),
    ]
