# Generated by Django 3.1.4 on 2021-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0023_auto_20210106_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
