# Generated by Django 3.1.4 on 2021-01-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0025_auto_20210112_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card_number',
            field=models.IntegerField(null=True),
        ),
    ]
