# Generated by Django 3.1 on 2021-01-12 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0026_auto_20210112_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Visa', 'Visa')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_card_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marketplace.seller'),
        ),
    ]
