# Generated by Django 3.1 on 2021-01-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0027_auto_20210113_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit_card_number',
            field=models.IntegerField(null=True),
        ),
    ]
