# Generated by Django 3.1 on 2021-01-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0029_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to=''),
        ),
    ]
