# Generated by Django 3.2.9 on 2021-12-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0031_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='money',
            field=models.IntegerField(default=30),
        ),
    ]
