# Generated by Django 3.2.9 on 2021-12-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0033_seller_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='checkout',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marketplace.seller'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Marketplace.seller'),
        ),
    ]
