# Generated by Django 2.2.24 on 2021-12-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0034_auto_20211207_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.IntegerField(null=True),
        ),
    ]
