# Generated by Django 2.2.24 on 2021-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0037_purchase_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='seller',
            field=models.IntegerField(null=True),
        ),
    ]
