# Generated by Django 2.2.24 on 2021-12-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_auto_20211228_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, default='empty.jpg', null=True, upload_to='')),
            ],
        ),
    ]
